### ISSUE TITLE
if parsed[0][1] IndexError??

### ISSUE THREAD

**Issue by L1ght5h0w** [jagrosh/FrostCleverbot#1]
The script file I have is pretty much the same as frost.py except my token, but I get the following error:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\frost5.py", line 22, in on_message
    await client.send_message(message.channel, cb.ask(message.content.replace(message.server.me.mention, '')) )
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cleverbot\cleverbot.py", line 104, in ask
    parsed = self._parse(resp.text)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cleverbot\cleverbot.py", line 156, in _parse
    if parsed[0][1] == 'DENIED':
IndexError: list index out of range
```

**Comment by L1ght5h0w** [comment]
Nvm. Fixed by changing cleverbot.py
Anyone else who has this issue:
The fix can be done by changing the `RESOURCE = "/webservicemin?uc=321&"` line to `RESOURCE = "/webservicemin?uc=3210&botapi=[YOUR_API_NAME]"` where you put a new name instead of `[YOUR_API_NAME]`.

**Comment by jagrosh** [comment]
You can also just update the cleverbot module for the same fix
