### ISSUE TITLE
no attribute 'send_typing'

### ISSUE THREAD

**Issue by QuickMythril** [jagrosh/FrostCleverbot#15]
when i send a PM to the bot i get no response, and this in the log:
`Ignoring exception in on_message`
`Traceback (most recent call last):`
`  File "C:\Users\QuickMythril\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 312, in _run_event`
`    await coro(*args, **kwargs)`
`  File "C:\loubot\frost2.py", line 10, in on_message`
`    await self.send_typing(message.channel)`
`AttributeError: 'FrostCleverbot' object has no attribute 'send_typing'`

apparently line 10:
await self.send_typing(message.channel)

needs to be updated to use:
"abc.Messageable.typing()"

**Comment by QuickMythril** [comment]
resolved by using the 1.2.2 update in pull requests.
